# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-05-19 18:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# orb.review.migrations.0003_update_pending_status

class Migration(migrations.Migration):

    replaces = [('review', '0001_initial'), ('review', '0002_auto_20161017_0013'), ('review', '0003_update_pending_status'), ('review', '0004_auto_20180501_1654')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orb', '0001_squashed_0058_auto_20200518_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', django_fsm.FSMField(default=b'pending_crt', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('criteria', models.ManyToManyField(blank=True, to='orb.ResourceCriteria')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_reviews', to='orb.Resource')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='orb.ReviewerRole')),
            ],
            options={
                'verbose_name': 'content review',
                'verbose_name_plural': 'content reviews',
            },
        ),
        migrations.CreateModel(
            name='ReviewLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('review_status', models.CharField(editable=False, max_length=20)),
                ('action', models.CharField(max_length=200)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='review.ContentReview')),
            ],
            options={
                'verbose_name': 'review log entry',
                'verbose_name_plural': 'review log entries',
            },
        ),
        migrations.AlterUniqueTogether(
            name='contentreview',
            unique_together=set([('resource', 'role')]),
        ),
        migrations.AlterField(
            model_name='contentreview',
            name='status',
            field=django_fsm.FSMField(default='pending', max_length=50),
        ),
    ]
