# Generated by Django 2.2.12 on 2020-06-02 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', django_fsm.FSMField(default='pending', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('criteria', models.ManyToManyField(blank=True, to='orb.ResourceCriteria')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_reviews', to='orb.Resource')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='orb.ReviewerRole')),
            ],
            options={
                'verbose_name': 'content review',
                'verbose_name_plural': 'content reviews',
                'unique_together': {('resource', 'role')},
            },
            managers=[
                ('reviews', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ReviewLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('review_status', models.CharField(editable=False, max_length=20)),
                ('action', models.CharField(max_length=200)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='review.ContentReview')),
            ],
            options={
                'verbose_name': 'review log entry',
                'verbose_name_plural': 'review log entries',
            },
        ),
    ]
