# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-05-22 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orb', '0001_squashed_0058_auto_20200518_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='source_peer',
            field=models.ForeignKey(blank=True, help_text='The peer ORB from which the resource was downloaded.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='peers.Peer'),
        ),
        migrations.AlterField(
            model_name='resourceworkflowtracker',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_trackers', to='orb.Resource'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='parent_tag',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='orb.Tag'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organisation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisation', to='orb.Tag'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role', to='orb.Tag'),
        ),
    ]
