# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-04-09 07:12
from __future__ import unicode_literals

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orb', '0055_resourcefile_sha1'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('categories', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
