# Generated by Django 2.2.10 on 2020-03-28 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import orb.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orb', '0055_resourcefile_sha1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('published', 'published'), ('archived', 'archived')], default='draft', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('sections', models.TextField(default='[]')),
                ('version', models.IntegerField(default=1, editable=False)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_create_user', to=settings.AUTH_USER_MODEL)),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_update_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('courses', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('categories', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='resource',
            name='source_peer',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=orb.fields.AutoSlugField(blank=True, editable=False, max_length=100, null=True, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='collection/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=orb.fields.AutoSlugField(blank=True, editable=False, max_length=255, null=True, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='resourceimage/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='slug',
            field=orb.fields.AutoSlugField(blank=True, editable=False, max_length=100, null=True, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='study_time_unit',
            field=models.CharField(blank=True, choices=[('mins', 'Mins'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='resourcecriteria',
            name='category',
            field=models.CharField(blank=True, choices=[('qa', 'Quality Assurance'), ('value', 'Value for Frontline Health Workers (FLHW)'), ('video', 'Video resources'), ('animation', 'Animation resources'), ('audio', 'Audio resources'), ('text', 'Text based resources')], help_text='deprecated', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resourcefile',
            name='file',
            field=models.FileField(max_length=200, upload_to='resource/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='resourcefile',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='resourceimage/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='resourcerelationship',
            name='relationship_type',
            field=models.CharField(choices=[('is_translation_of', 'is translation of'), ('is_derivative_of', 'is derivative of'), ('is_contained_in', 'is contained in')], max_length=50),
        ),
        migrations.AlterField(
            model_name='resourcetracker',
            name='survey_intended_use_other',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='resourcetracker',
            name='type',
            field=models.CharField(choices=[('view', 'View'), ('view-api', 'View-api'), ('edit', 'Edit'), ('download', 'Download'), ('create', 'Create')], default='view', max_length=50),
        ),
        migrations.AlterField(
            model_name='resourceurl',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='resourceimage/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='resourceworkflowtracker',
            name='create_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resourceworkflowtracker',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='reviewerrole',
            name='name',
            field=models.CharField(choices=[('medical', 'Medical'), ('technical', 'Technical'), ('training', 'Training')], default='medical', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='searchtracker',
            name='type',
            field=models.CharField(choices=[('search', 'search'), ('search-api', 'search-api'), ('search-adv', 'search-adv')], default='search', max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orb.Category'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tag/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='published',
            field=models.BooleanField(default=True, help_text='Used to toggle status of health domains.'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=orb.fields.AutoSlugField(blank=True, editable=False, max_length=100, null=True, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='tagtracker',
            name='type',
            field=models.CharField(choices=[('view', 'View'), ('view-api', 'View-API'), ('view-url', 'View-URL')], default='view', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age_range',
            field=models.CharField(choices=[('under_18', 'under 18'), ('18_25', '18-24'), ('25_35', '25-34'), ('35_50', '35-50'), ('over_50', 'over 50'), ('none', 'Prefer not to say')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('none', 'Prefer not to say')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='userprofile/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role', to='orb.Tag'),
        ),
        migrations.CreateModel(
            name='OppiaLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('oppia_host', models.URLField()),
                ('status', models.SmallIntegerField(help_text='HTTP status code of the response')),
                ('success', models.BooleanField(default=False)),
                ('response', models.TextField(blank=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oppia_logs', to='orb.Course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oppia_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
