# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-04-20 06:57
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orb', '0056_auto_20200409_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description_es',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description_pt_br',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
    ]
