# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-05-18 11:42
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('orb', '0057_auto_20200420_0657'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('categories', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='resource',
            managers=[
                ('resources', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='resourcecriteria',
            managers=[
                ('criteria', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='tag',
            managers=[
                ('tags', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_pt_br',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='attribution_es',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='attribution_pt_br',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='description_pt_br',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='title_pt_br',
        ),
        migrations.RemoveField(
            model_name='resourcecriteria',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='resourcecriteria',
            name='description_pt_br',
        ),
        migrations.RemoveField(
            model_name='resourcefile',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='resourcefile',
            name='description_pt_br',
        ),
        migrations.RemoveField(
            model_name='resourcefile',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='resourcefile',
            name='title_pt_br',
        ),
        migrations.RemoveField(
            model_name='resourceurl',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='resourceurl',
            name='description_pt_br',
        ),
        migrations.RemoveField(
            model_name='resourceurl',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='resourceurl',
            name='title_pt_br',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='description_pt_br',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name_pt_br',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='summary_es',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='summary_pt_br',
        ),
    ]
