# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-05-19 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('peers', '0001_initial'), ('peers', '0002_api_credentials'), ('peers', '0003_auto_20170220_2036'), ('peers', '0004_auto_20180501_1654')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('host', models.URLField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeerQueryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('finished', models.DateTimeField(blank=True, editable=False, null=True)),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='peers.Peer')),
                ('filtered_date', models.DateTimeField(blank=True, null=True)),
                ('new_resources', models.PositiveIntegerField(null=True)),
                ('skipped_local_resources', models.PositiveIntegerField(null=True)),
                ('unchanged_resources', models.PositiveIntegerField(null=True)),
                ('updated_resources', models.PositiveIntegerField(null=True)),
            ],
            options={
                'get_latest_by': 'finished',
            },
        ),
        migrations.AddField(
            model_name='peer',
            name='api_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='peer',
            name='api_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelManagers(
            name='peer',
            managers=[
                ('peers', django.db.models.manager.Manager()),
            ],
        ),
    ]
