# Generated by Django 2.2.12 on 2020-06-02 16:55

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('host', models.URLField()),
                ('active', models.BooleanField(default=True)),
                ('api_user', models.CharField(blank=True, max_length=100, null=True)),
                ('api_key', models.CharField(blank=True, max_length=100, null=True)),
            ],
            managers=[
                ('peers', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PeerQueryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('finished', models.DateTimeField(blank=True, editable=False, null=True)),
                ('filtered_date', models.DateTimeField(blank=True, null=True)),
                ('new_resources', models.PositiveIntegerField(null=True)),
                ('skipped_local_resources', models.PositiveIntegerField(null=True)),
                ('updated_resources', models.PositiveIntegerField(null=True)),
                ('unchanged_resources', models.PositiveIntegerField(null=True)),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='peers.Peer')),
            ],
            options={
                'get_latest_by': 'finished',
            },
            managers=[
                ('entries', django.db.models.manager.Manager()),
            ],
        ),
    ]
