# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-01 16:54
from __future__ import unicode_literals

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peers', '0003_auto_20170220_2036'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='peer',
            managers=[
                ('peers', django.db.models.manager.Manager()),
            ],
        ),
    ]
