# Generated by Django 2.2.10 on 2020-03-28 20:01

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('peers', '0004_auto_20180501_1654'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='peerquerylog',
            managers=[
                ('entries', django.db.models.manager.Manager()),
            ],
        ),
    ]
