# Generated by Django 2.2.10 on 2020-03-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkits', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolkit',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
